'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PT_ConMat_Dev
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZPPMXF002SoapBinding", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZPPMXF002Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZPPMXF002OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Atlas.My.MySettings.Default.A_tlas_PT_ConMat_Dev_ZPPMXF002Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZPPMXF002Completed As ZPPMXF002CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="urn:sap-com:document:sap:rfc:functions", ResponseNamespace:="urn:sap-com:document:sap:rfc:functions", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ZPPMXF002(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal PA_TEXTO As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TEXT_COMPONENTS As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ZINPUT As ZEPP002, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef ZRETURN As ZBAPIRET2) As <System.Xml.Serialization.XmlElementAttribute("ZOUTPUT", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _ISDFPS_TCUPS_KEY
            Dim results() As Object = Me.Invoke("ZPPMXF002", New Object() {PA_TEXTO, TEXT_COMPONENTS, ZINPUT})
            ZRETURN = CType(results(1),ZBAPIRET2)
            Return CType(results(0),_ISDFPS_TCUPS_KEY)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZPPMXF002Async(ByVal PA_TEXTO As String, ByVal TEXT_COMPONENTS As String, ByVal ZINPUT As ZEPP002)
            Me.ZPPMXF002Async(PA_TEXTO, TEXT_COMPONENTS, ZINPUT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZPPMXF002Async(ByVal PA_TEXTO As String, ByVal TEXT_COMPONENTS As String, ByVal ZINPUT As ZEPP002, ByVal userState As Object)
            If (Me.ZPPMXF002OperationCompleted Is Nothing) Then
                Me.ZPPMXF002OperationCompleted = AddressOf Me.OnZPPMXF002OperationCompleted
            End If
            Me.InvokeAsync("ZPPMXF002", New Object() {PA_TEXTO, TEXT_COMPONENTS, ZINPUT}, Me.ZPPMXF002OperationCompleted, userState)
        End Sub
        
        Private Sub OnZPPMXF002OperationCompleted(ByVal arg As Object)
            If (Not (Me.ZPPMXF002CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZPPMXF002Completed(Me, New ZPPMXF002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9014.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZEPP002
        
        Private zORDERIDField As String
        
        Private zBUDATField As String
        
        Private zENTRY_QNTField As Decimal
        
        Private zISM01Field As Decimal
        
        Private zISM02Field As Decimal
        
        Private zISM03Field As Decimal
        
        Private zISMNGEH1Field As String
        
        Private zISMNGEH2Field As String
        
        Private zISMNGEH3Field As String
        
        Private zVIRGINField As Decimal
        
        Private zRECOVEREDField As Decimal
        
        Private zMATNR_RECField As String
        
        Private zCONSUME_RECField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZORDERID() As String
            Get
                Return Me.zORDERIDField
            End Get
            Set
                Me.zORDERIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZBUDAT() As String
            Get
                Return Me.zBUDATField
            End Get
            Set
                Me.zBUDATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZENTRY_QNT() As Decimal
            Get
                Return Me.zENTRY_QNTField
            End Get
            Set
                Me.zENTRY_QNTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISM01() As Decimal
            Get
                Return Me.zISM01Field
            End Get
            Set
                Me.zISM01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISM02() As Decimal
            Get
                Return Me.zISM02Field
            End Get
            Set
                Me.zISM02Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISM03() As Decimal
            Get
                Return Me.zISM03Field
            End Get
            Set
                Me.zISM03Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISMNGEH1() As String
            Get
                Return Me.zISMNGEH1Field
            End Get
            Set
                Me.zISMNGEH1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISMNGEH2() As String
            Get
                Return Me.zISMNGEH2Field
            End Get
            Set
                Me.zISMNGEH2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZISMNGEH3() As String
            Get
                Return Me.zISMNGEH3Field
            End Get
            Set
                Me.zISMNGEH3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZVIRGIN() As Decimal
            Get
                Return Me.zVIRGINField
            End Get
            Set
                Me.zVIRGINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZRECOVERED() As Decimal
            Get
                Return Me.zRECOVEREDField
            End Get
            Set
                Me.zRECOVEREDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMATNR_REC() As String
            Get
                Return Me.zMATNR_RECField
            End Get
            Set
                Me.zMATNR_RECField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZCONSUME_REC() As Decimal
            Get
                Return Me.zCONSUME_RECField
            End Get
            Set
                Me.zCONSUME_RECField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9014.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZBAPIRET2
        
        Private zTYPEField As String
        
        Private zIDField As String
        
        Private zNUMBERField As String
        
        Private zMESSAGEField As String
        
        Private zLOG_NOField As String
        
        Private zLOG_MSG_NOField As String
        
        Private zMESSAGE_V1Field As String
        
        Private zMESSAGE_V2Field As String
        
        Private zMESSAGE_V3Field As String
        
        Private zMESSAGE_V4Field As String
        
        Private zPARAMETERField As String
        
        Private zROWField As Integer
        
        Private zFIELDField As String
        
        Private zSYSTEMField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZTYPE() As String
            Get
                Return Me.zTYPEField
            End Get
            Set
                Me.zTYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZID() As String
            Get
                Return Me.zIDField
            End Get
            Set
                Me.zIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZNUMBER() As String
            Get
                Return Me.zNUMBERField
            End Get
            Set
                Me.zNUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE() As String
            Get
                Return Me.zMESSAGEField
            End Get
            Set
                Me.zMESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_NO() As String
            Get
                Return Me.zLOG_NOField
            End Get
            Set
                Me.zLOG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_MSG_NO() As String
            Get
                Return Me.zLOG_MSG_NOField
            End Get
            Set
                Me.zLOG_MSG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V1() As String
            Get
                Return Me.zMESSAGE_V1Field
            End Get
            Set
                Me.zMESSAGE_V1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V2() As String
            Get
                Return Me.zMESSAGE_V2Field
            End Get
            Set
                Me.zMESSAGE_V2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V3() As String
            Get
                Return Me.zMESSAGE_V3Field
            End Get
            Set
                Me.zMESSAGE_V3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V4() As String
            Get
                Return Me.zMESSAGE_V4Field
            End Get
            Set
                Me.zMESSAGE_V4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPARAMETER() As String
            Get
                Return Me.zPARAMETERField
            End Get
            Set
                Me.zPARAMETERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZROW() As Integer
            Get
                Return Me.zROWField
            End Get
            Set
                Me.zROWField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZFIELD() As String
            Get
                Return Me.zFIELDField
            End Get
            Set
                Me.zFIELDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZSYSTEM() As String
            Get
                Return Me.zSYSTEMField
            End Get
            Set
                Me.zSYSTEMField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9014.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="_-ISDFPS_-TCUPS_KEY", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class _ISDFPS_TCUPS_KEY
        
        Private rUECKField As String
        
        Private rMZHLField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RUECK() As String
            Get
                Return Me.rUECKField
            End Get
            Set
                Me.rUECKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RMZHL() As String
            Get
                Return Me.rMZHLField
            End Get
            Set
                Me.rMZHLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0")>  _
    Public Delegate Sub ZPPMXF002CompletedEventHandler(ByVal sender As Object, ByVal e As ZPPMXF002CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZPPMXF002CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As _ISDFPS_TCUPS_KEY
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),_ISDFPS_TCUPS_KEY)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ZRETURN() As ZBAPIRET2
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),ZBAPIRET2)
            End Get
        End Property
    End Class
End Namespace
