'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MEMXSLPW001;Initial Catalog=bdmcp_2;User ID=UsrLibra")>  _
        Public ReadOnly Property bdmcp_2ConnectionString() As String
            Get
                Return CType(Me("bdmcp_2ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MEMXSLPW001;Initial Catalog=bdmcp;User ID=UsrLibra")>  _
        Public ReadOnly Property bdmcpConnectionString() As String
            Get
                Return CType(Me("bdmcpConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MEMXSLPW001;Initial Catalog=Usuarios;User ID=UsrLibra")>  _
        Public ReadOnly Property UsuariosConnectionString() As String
            Get
                Return CType(Me("UsuariosConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/ZSDMX_READ_SCALE_DOCUME"& _ 
            "NTS?sap-client=300")>  _
        Public ReadOnly Property A_tlas_Leer_Pedido_ZSDMX_READ_SCALE_DOCUMENTSService() As String
            Get
                Return CType(Me("A_tlas_Leer_Pedido_ZSDMX_READ_SCALE_DOCUMENTSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrate"& _ 
            "d Security=True;User Instance=True")>  _
        Public ReadOnly Property Database1ConnectionString() As String
            Get
                Return CType(Me("Database1ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=memxslpw026;Initial Catalog=Amanco;Integrated Security=True")>  _
        Public ReadOnly Property AmancoConnectionString() As String
            Get
                Return CType(Me("AmancoConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/ZPPMXF002?sap-client=30"& _ 
            "0")>  _
        Public ReadOnly Property A_tlas_PT_ConMat_Dev_ZPPMXF002Service() As String
            Get
                Return CType(Me("A_tlas_PT_ConMat_Dev_ZPPMXF002Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/ZPPMXF001?sap-client=30"& _ 
            "0")>  _
        Public ReadOnly Property A_tlas_PTConsumos_ZPPMXF001Service() As String
            Get
                Return CType(Me("A_tlas_PTConsumos_ZPPMXF001Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/zglmx_atlas_gr/300/zglm"& _ 
            "x_atlas_gr/zglmx_atlas_gr")>  _
        Public ReadOnly Property A_tlas_Dev_Materials_ZGLMX_ATLAS_GRService() As String
            Get
                Return CType(Me("A_tlas_Dev_Materials_ZGLMX_ATLAS_GRService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/ZSDMX_POST_SCALE_DATA?s"& _ 
            "ap-client=300")>  _
        Public ReadOnly Property A_tlas_Graba_Pedido_ZSDMX_POST_SCALE_DATAService() As String
            Get
                Return CType(Me("A_tlas_Graba_Pedido_ZSDMX_POST_SCALE_DATAService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/zppgl_read_order_300/30"& _ 
            "0/zppgl_read_order_300/zppgl_read_order_300")>  _
        Public ReadOnly Property A_tlas_Dev_Read_ODF_ZPPGL_READ_ORDER_300() As String
            Get
                Return CType(Me("A_tlas_Dev_Read_ODF_ZPPGL_READ_ORDER_300"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mxslx140.mexichem.corp:8001/sap/bc/srt/rfc/sap/ZPP003_91?sap-client=300")>  _
        Public ReadOnly Property A_tlas_Graba_OF_ZPP003_91Service() As String
            Get
                Return CType(Me("A_tlas_Graba_OF_ZPP003_91Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mxslx140.mexichem.corp:8001/sap/bc/srt/rfc/sap/ZPP001_91?sap-client=300")>  _
        Public ReadOnly Property A_tlas_Lee_OFP_ZPP001_91Service() As String
            Get
                Return CType(Me("A_tlas_Lee_OFP_ZPP001_91Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mxslx140.mexichem.corp:8001/sap/bc/srt/rfc/sap/ZPPMXF001?sap-client=300")>  _
        Public ReadOnly Property A_tlas_PTConProd_ZPPMXF001Service() As String
            Get
                Return CType(Me("A_tlas_PTConProd_ZPPMXF001Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcip010000.mexichem.corp:8001/sap/bc/srt/rfc/sap/zglmx_atlas_gr/300/zglm"& _ 
            "x_atlas_gr/zglmx_atlas_gr")>  _
        Public ReadOnly Property A_tlas_Prd_Gen_ZGLMX_ATLAS_GR() As String
            Get
                Return CType(Me("A_tlas_Prd_Gen_ZGLMX_ATLAS_GR"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mxslx140.mexichem.corp:8001/sap/bc/srt/rfc/sap/ZPPMXF002?sap-client=300")>  _
        Public ReadOnly Property A_tlas_PT_ConMat_Prod_ZPPMXF002Service() As String
            Get
                Return CType(Me("A_tlas_PT_ConMat_Prod_ZPPMXF002Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mexcid010000.mexichem.corp:8000/sap/bc/srt/rfc/sap/ZPP001_91?sap-client=30"& _ 
            "0")>  _
        Public ReadOnly Property A_tlas_Read_ZPP001_91Service() As String
            Get
                Return CType(Me("A_tlas_Read_ZPP001_91Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M")>  _
        Public Property Bascula_1() As String
            Get
                Return CType(Me("Bascula_1"),String)
            End Get
            Set
                Me("Bascula_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M")>  _
        Public Property Bascula_2() As String
            Get
                Return CType(Me("Bascula_2"),String)
            End Get
            Set
                Me("Bascula_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M")>  _
        Public Property Bascula_3() As String
            Get
                Return CType(Me("Bascula_3"),String)
            End Get
            Set
                Me("Bascula_3") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Atlas.My.MySettings
            Get
                Return Global.Atlas.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
