'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Dev_Read_ODF
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZPPGL_READ_ORDER_300", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZPPGL_READ_ORDER_300
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Z_PPMXCO03OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Atlas.My.MySettings.Default.A_tlas_Dev_Read_ODF_ZPPGL_READ_ORDER_300
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Z_PPMXCO03Completed As Z_PPMXCO03CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="urn:sap-com:document:sap:rfc:functions", ResponseNamespace:="urn:sap-com:document:sap:rfc:functions", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Z_PPMXCO03(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ZNUMBER As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ZTRANSAC As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef ZORDER_DATA As ZEPP001, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef ZOUTPUT As _ISDFPS_TCUPS_KEY, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef ZRETURN As ZBAPIRET2) As <System.Xml.Serialization.XmlElementAttribute("ZADDITIONAL", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> String
            Dim results() As Object = Me.Invoke("Z_PPMXCO03", New Object() {ZNUMBER, ZTRANSAC})
            ZORDER_DATA = CType(results(1),ZEPP001)
            ZOUTPUT = CType(results(2),_ISDFPS_TCUPS_KEY)
            ZRETURN = CType(results(3),ZBAPIRET2)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Z_PPMXCO03Async(ByVal ZNUMBER As String, ByVal ZTRANSAC As String)
            Me.Z_PPMXCO03Async(ZNUMBER, ZTRANSAC, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Z_PPMXCO03Async(ByVal ZNUMBER As String, ByVal ZTRANSAC As String, ByVal userState As Object)
            If (Me.Z_PPMXCO03OperationCompleted Is Nothing) Then
                Me.Z_PPMXCO03OperationCompleted = AddressOf Me.OnZ_PPMXCO03OperationCompleted
            End If
            Me.InvokeAsync("Z_PPMXCO03", New Object() {ZNUMBER, ZTRANSAC}, Me.Z_PPMXCO03OperationCompleted, userState)
        End Sub
        
        Private Sub OnZ_PPMXCO03OperationCompleted(ByVal arg As Object)
            If (Not (Me.Z_PPMXCO03CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Z_PPMXCO03Completed(Me, New Z_PPMXCO03CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZEPP001
        
        Private zORDER_NUMBERField As String
        
        Private zPRODUCTION_PLANTField As String
        
        Private zWORK_CENTERField As String
        
        Private zMATERIALField As String
        
        Private zTARGET_QUANTITYField As Decimal
        
        Private zUNITField As String
        
        Private zSTART_DATEField As String
        
        Private zFINISH_DATEField As String
        
        Private zORIGINField As String
        
        Private zSTATUSField As String
        
        Private zACTUAL_START_DATEField As String
        
        Private zACTUAL_START_TIMEField As String
        
        Private zACTUAL_FINISH_DATEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZORDER_NUMBER() As String
            Get
                Return Me.zORDER_NUMBERField
            End Get
            Set
                Me.zORDER_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPRODUCTION_PLANT() As String
            Get
                Return Me.zPRODUCTION_PLANTField
            End Get
            Set
                Me.zPRODUCTION_PLANTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZWORK_CENTER() As String
            Get
                Return Me.zWORK_CENTERField
            End Get
            Set
                Me.zWORK_CENTERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMATERIAL() As String
            Get
                Return Me.zMATERIALField
            End Get
            Set
                Me.zMATERIALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZTARGET_QUANTITY() As Decimal
            Get
                Return Me.zTARGET_QUANTITYField
            End Get
            Set
                Me.zTARGET_QUANTITYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZUNIT() As String
            Get
                Return Me.zUNITField
            End Get
            Set
                Me.zUNITField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZSTART_DATE() As String
            Get
                Return Me.zSTART_DATEField
            End Get
            Set
                Me.zSTART_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZFINISH_DATE() As String
            Get
                Return Me.zFINISH_DATEField
            End Get
            Set
                Me.zFINISH_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZORIGIN() As String
            Get
                Return Me.zORIGINField
            End Get
            Set
                Me.zORIGINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZSTATUS() As String
            Get
                Return Me.zSTATUSField
            End Get
            Set
                Me.zSTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZACTUAL_START_DATE() As String
            Get
                Return Me.zACTUAL_START_DATEField
            End Get
            Set
                Me.zACTUAL_START_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZACTUAL_START_TIME() As String
            Get
                Return Me.zACTUAL_START_TIMEField
            End Get
            Set
                Me.zACTUAL_START_TIMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZACTUAL_FINISH_DATE() As String
            Get
                Return Me.zACTUAL_FINISH_DATEField
            End Get
            Set
                Me.zACTUAL_FINISH_DATEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZBAPIRET2
        
        Private zTYPEField As String
        
        Private zIDField As String
        
        Private zNUMBERField As String
        
        Private zMESSAGEField As String
        
        Private zLOG_NOField As String
        
        Private zLOG_MSG_NOField As String
        
        Private zMESSAGE_V1Field As String
        
        Private zMESSAGE_V2Field As String
        
        Private zMESSAGE_V3Field As String
        
        Private zMESSAGE_V4Field As String
        
        Private zPARAMETERField As String
        
        Private zROWField As Integer
        
        Private zFIELDField As String
        
        Private zSYSTEMField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZTYPE() As String
            Get
                Return Me.zTYPEField
            End Get
            Set
                Me.zTYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZID() As String
            Get
                Return Me.zIDField
            End Get
            Set
                Me.zIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZNUMBER() As String
            Get
                Return Me.zNUMBERField
            End Get
            Set
                Me.zNUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE() As String
            Get
                Return Me.zMESSAGEField
            End Get
            Set
                Me.zMESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_NO() As String
            Get
                Return Me.zLOG_NOField
            End Get
            Set
                Me.zLOG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_MSG_NO() As String
            Get
                Return Me.zLOG_MSG_NOField
            End Get
            Set
                Me.zLOG_MSG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V1() As String
            Get
                Return Me.zMESSAGE_V1Field
            End Get
            Set
                Me.zMESSAGE_V1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V2() As String
            Get
                Return Me.zMESSAGE_V2Field
            End Get
            Set
                Me.zMESSAGE_V2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V3() As String
            Get
                Return Me.zMESSAGE_V3Field
            End Get
            Set
                Me.zMESSAGE_V3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V4() As String
            Get
                Return Me.zMESSAGE_V4Field
            End Get
            Set
                Me.zMESSAGE_V4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPARAMETER() As String
            Get
                Return Me.zPARAMETERField
            End Get
            Set
                Me.zPARAMETERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZROW() As Integer
            Get
                Return Me.zROWField
            End Get
            Set
                Me.zROWField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZFIELD() As String
            Get
                Return Me.zFIELDField
            End Get
            Set
                Me.zFIELDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZSYSTEM() As String
            Get
                Return Me.zSYSTEMField
            End Get
            Set
                Me.zSYSTEMField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="_-ISDFPS_-TCUPS_KEY", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class _ISDFPS_TCUPS_KEY
        
        Private rUECKField As String
        
        Private rMZHLField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RUECK() As String
            Get
                Return Me.rUECKField
            End Get
            Set
                Me.rUECKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RMZHL() As String
            Get
                Return Me.rMZHLField
            End Get
            Set
                Me.rMZHLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub Z_PPMXCO03CompletedEventHandler(ByVal sender As Object, ByVal e As Z_PPMXCO03CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Z_PPMXCO03CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ZORDER_DATA() As ZEPP001
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),ZEPP001)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ZOUTPUT() As _ISDFPS_TCUPS_KEY
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),_ISDFPS_TCUPS_KEY)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ZRETURN() As ZBAPIRET2
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),ZBAPIRET2)
            End Get
        End Property
    End Class
End Namespace
