'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Graba_Pedido
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZSDMX_POST_SCALE_DATASoapBinding", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSDMX_POST_SCALE_DATAService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Z_SDMX_POST_SCALE_DATAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Atlas.My.MySettings.Default.A_tlas_Graba_Pedido_ZSDMX_POST_SCALE_DATAService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Z_SDMX_POST_SCALE_DATACompleted As Z_SDMX_POST_SCALE_DATACompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="urn:sap-com:document:sap:rfc:functions", ResponseNamespace:="urn:sap-com:document:sap:rfc:functions", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Z_SDMX_POST_SCALE_DATA(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ZDOCUMENT_TO_SEARCH As ZSDMXS001, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ZINPUT As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByRef ZRETURN As ZBAPIRET2) As <System.Xml.Serialization.XmlElementAttribute("ZOUTPUT", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> String
            Dim results() As Object = Me.Invoke("Z_SDMX_POST_SCALE_DATA", New Object() {ZDOCUMENT_TO_SEARCH, ZINPUT})
            ZRETURN = CType(results(1),ZBAPIRET2)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Z_SDMX_POST_SCALE_DATAAsync(ByVal ZDOCUMENT_TO_SEARCH As ZSDMXS001, ByVal ZINPUT As String)
            Me.Z_SDMX_POST_SCALE_DATAAsync(ZDOCUMENT_TO_SEARCH, ZINPUT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Z_SDMX_POST_SCALE_DATAAsync(ByVal ZDOCUMENT_TO_SEARCH As ZSDMXS001, ByVal ZINPUT As String, ByVal userState As Object)
            If (Me.Z_SDMX_POST_SCALE_DATAOperationCompleted Is Nothing) Then
                Me.Z_SDMX_POST_SCALE_DATAOperationCompleted = AddressOf Me.OnZ_SDMX_POST_SCALE_DATAOperationCompleted
            End If
            Me.InvokeAsync("Z_SDMX_POST_SCALE_DATA", New Object() {ZDOCUMENT_TO_SEARCH, ZINPUT}, Me.Z_SDMX_POST_SCALE_DATAOperationCompleted, userState)
        End Sub
        
        Private Sub OnZ_SDMX_POST_SCALE_DATAOperationCompleted(ByVal arg As Object)
            If (Not (Me.Z_SDMX_POST_SCALE_DATACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Z_SDMX_POST_SCALE_DATACompleted(Me, New Z_SDMX_POST_SCALE_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9014.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSDMXS001
        
        Private zDOCUMENT_TYPEField As String
        
        Private zDOCUMENT_NUMBERField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZDOCUMENT_TYPE() As String
            Get
                Return Me.zDOCUMENT_TYPEField
            End Get
            Set
                Me.zDOCUMENT_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZDOCUMENT_NUMBER() As String
            Get
                Return Me.zDOCUMENT_NUMBERField
            End Get
            Set
                Me.zDOCUMENT_NUMBERField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9014.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZBAPIRET2
        
        Private zTYPEField As String
        
        Private zIDField As String
        
        Private zNUMBERField As String
        
        Private zMESSAGEField As String
        
        Private zLOG_NOField As String
        
        Private zLOG_MSG_NOField As String
        
        Private zMESSAGE_V1Field As String
        
        Private zMESSAGE_V2Field As String
        
        Private zMESSAGE_V3Field As String
        
        Private zMESSAGE_V4Field As String
        
        Private zPARAMETERField As String
        
        Private zROWField As Integer
        
        Private zFIELDField As String
        
        Private zSYSTEMField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZTYPE() As String
            Get
                Return Me.zTYPEField
            End Get
            Set
                Me.zTYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZID() As String
            Get
                Return Me.zIDField
            End Get
            Set
                Me.zIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZNUMBER() As String
            Get
                Return Me.zNUMBERField
            End Get
            Set
                Me.zNUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE() As String
            Get
                Return Me.zMESSAGEField
            End Get
            Set
                Me.zMESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_NO() As String
            Get
                Return Me.zLOG_NOField
            End Get
            Set
                Me.zLOG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLOG_MSG_NO() As String
            Get
                Return Me.zLOG_MSG_NOField
            End Get
            Set
                Me.zLOG_MSG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V1() As String
            Get
                Return Me.zMESSAGE_V1Field
            End Get
            Set
                Me.zMESSAGE_V1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V2() As String
            Get
                Return Me.zMESSAGE_V2Field
            End Get
            Set
                Me.zMESSAGE_V2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V3() As String
            Get
                Return Me.zMESSAGE_V3Field
            End Get
            Set
                Me.zMESSAGE_V3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZMESSAGE_V4() As String
            Get
                Return Me.zMESSAGE_V4Field
            End Get
            Set
                Me.zMESSAGE_V4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPARAMETER() As String
            Get
                Return Me.zPARAMETERField
            End Get
            Set
                Me.zPARAMETERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZROW() As Integer
            Get
                Return Me.zROWField
            End Get
            Set
                Me.zROWField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZFIELD() As String
            Get
                Return Me.zFIELDField
            End Get
            Set
                Me.zFIELDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZSYSTEM() As String
            Get
                Return Me.zSYSTEMField
            End Get
            Set
                Me.zSYSTEMField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0")>  _
    Public Delegate Sub Z_SDMX_POST_SCALE_DATACompletedEventHandler(ByVal sender As Object, ByVal e As Z_SDMX_POST_SCALE_DATACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9014.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Z_SDMX_POST_SCALE_DATACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ZRETURN() As ZBAPIRET2
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),ZBAPIRET2)
            End Get
        End Property
    End Class
End Namespace
